# Generated by Django 5.1.15 on 2026-05-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Default Filter', max_length=255)),
                ('keywords', models.JSONField(blank=True, default=list, help_text='Vacancy must match at least one keyword')),
                ('excluded_keywords', models.JSONField(blank=True, default=list, help_text='Vacancy must NOT contain these keywords')),
                ('locations', models.JSONField(blank=True, default=list, help_text='Acceptable locations (city, country)')),
                ('work_format', models.CharField(blank=True, choices=[('remote', 'Remote'), ('onsite', 'On-site'), ('hybrid', 'Hybrid'), ('not_specified', 'Not specified')], max_length=20, null=True)),
                ('experience_level', models.CharField(blank=True, choices=[('intern', 'Intern'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('lead', 'Lead'), ('not_specified', 'Not specified')], max_length=20, null=True)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notify_on_match', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'User Filter',
                'verbose_name_plural': 'User Filters',
                'ordering': ['-created_at'],
            },
        ),
    ]
