# Generated by Django 5.1.15 on 2026-05-11 14:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('company_meta', models.JSONField(blank=True, default=dict)),
                ('location_raw', models.CharField(blank=True, default='', max_length=500)),
                ('location_normalized', models.CharField(blank=True, max_length=255, null=True)),
                ('salary_from', models.IntegerField(blank=True, null=True)),
                ('salary_to', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='RUB', max_length=10)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('internship', 'Internship')], default='full_time', max_length=20)),
                ('work_format', models.CharField(choices=[('remote', 'Remote'), ('onsite', 'On-site'), ('hybrid', 'Hybrid'), ('not_specified', 'Not specified')], default='not_specified', max_length=20)),
                ('experience_level', models.CharField(choices=[('intern', 'Intern'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('lead', 'Lead'), ('not_specified', 'Not specified')], default='not_specified', max_length=20)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('url', models.URLField(max_length=2048, unique=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancies', to='sources.source')),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancies',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='VacancyContent',
            fields=[
                ('vacancy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='content', serialize=False, to='vacancies.vacancy')),
                ('full_html', models.TextField(blank=True, default='')),
                ('full_text', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Vacancy Content',
                'verbose_name_plural': 'Vacancy Contents',
            },
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['published_at'], name='vacancy_published_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['source', 'external_id'], name='vacancy_source_ext_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['experience_level'], name='vacancy_level_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['work_format'], name='vacancy_format_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['salary_from', 'salary_to'], name='vacancy_salary_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['is_deleted'], name='vacancy_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vacancy',
            unique_together={('source', 'external_id')},
        ),
    ]
