# Generated by Django 5.1.15 on 2026-05-11 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filters', '0001_initial'),
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField(help_text='Match score from 0.0 to 1.0')),
                ('keyword_score', models.FloatField(default=0.0)),
                ('location_score', models.FloatField(default=0.0)),
                ('salary_score', models.FloatField(default=0.0)),
                ('experience_score', models.FloatField(default=0.0)),
                ('is_notified', models.BooleanField(default=False)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='filters.userfilter')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='vacancies.vacancy')),
            ],
            options={
                'verbose_name': 'Vacancy Match',
                'verbose_name_plural': 'Vacancy Matches',
                'ordering': ['-score', '-created_at'],
                'indexes': [models.Index(fields=['filter', 'is_notified'], name='match_filter_notified_idx'), models.Index(fields=['score'], name='match_score_idx')],
                'unique_together': {('vacancy', 'filter')},
            },
        ),
    ]
