# Generated by Django 5.1.15 on 2026-05-11 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('source_type', models.CharField(choices=[('api', 'API'), ('scraping', 'Web Scraping'), ('telegram', 'Telegram Channel'), ('rss', 'RSS Feed')], default='api', max_length=20)),
                ('base_url', models.URLField()),
                ('rate_limit', models.PositiveIntegerField(default=1, help_text='Max requests per second')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Source-specific configuration (API keys, headers, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('last_parsed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ParsingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], default='started', max_length=20)),
                ('parsed_count', models.IntegerField(default=0)),
                ('new_count', models.IntegerField(default=0)),
                ('duplicate_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsing_logs', to='sources.source')),
            ],
            options={
                'verbose_name': 'Parsing Log',
                'verbose_name_plural': 'Parsing Logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['source', 'started_at'], name='parselog_source_idx'), models.Index(fields=['status'], name='parselog_status_idx')],
            },
        ),
    ]
