# --- Jazzmin Settings (Premium Admin) ----------------------------------------
JAZZMIN_SETTINGS = {
    "site_title": "JobPulse Admin",
    "site_header": "JobPulse",
    "site_brand": "JobPulse Control",
    "welcome_sign": "Welcome to JobPulse Management",
    "copyright": "JobPulse Ltd",
    "search_model": ["users.User", "vacancies.Vacancy"],
    "user_avatar": None,
    # --- Navigation -------------------------------------------------------------
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "API Docs", "url": "schema-swagger-ui", "new_window": True},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["users", "vacancies", "sources", "matching", "notifications"],
    "icons": {
        "auth": "fas fa-users-cog",
        "users.User": "fas fa-user",
        "users.TelegramProfile": "fab fa-telegram",
        "vacancies.Vacancy": "fas fa-briefcase",
        "sources.Source": "fas fa-database",
        "matching.VacancyMatch": "fas fa-check-double",
        "notifications.NotificationQueue": "fas fa-bell",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    # --- UI Tweaks --------------------------------------------------------------
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_fixed": True,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_patch_height": False,
    "sidebar_link_nav_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
}
